apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: grupo6
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 30016
    targetPort: 8000
    name: http
  - protocol: TCP
    port: 30036
    targetPort: 9090
    name: metrics
  type: LoadBalancer 