apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: grupo6
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 30026
    targetPort: 80 
  type: LoadBalancer 
